package com.vasylyev.hometasks.model.enums;

public enum SettingType {
    TELEGRAM_BOT_NAME,
    TELEGRAM_BOT_USERNAME,
    TELEGRAM_BOT_TOKEN,
    GOOGLE_APP_NAME,
    GOOGLE_APP_CREDENTIALS,
    GOOGLE_CLASSROOM_TOKEN_DIR,
    GOOGLE_SHEETS_TOKEN_DIR,
    GOOGLE_SHEETS_SPREADSHEET_ID,
    JOB_GET_COURSES_STATUS,
    JOB_GET_COURSES_HISTORY_STATUS,
    GOOGLE_SHEETS_USE_STATUS
}
