package com.vasylyev.hometasks.model.enums;

public enum SettingType {
    TELEGRAM_BOT_NAME
    , TELEGRAM_BOT_USERNAME
    , TELEGRAM_BOT_TOKEN
    , GOOGLE_APP_NAME
    , GOOGLE_CLASSROOM_TOKEN_DIR
    , GOOGLE_SHEETS_TOKEN_DIR
    , GOOGLE_CLASSROOM_TOKEN_CREDENTIALS
    , GOOGLE_SHEETS_TOKEN_CREDENTIALS
    , GOOGLE_SHEETS_SPREADSHEET_ID
}
